import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import { Appbar } from "./component/Appbar";
import { getServerSession } from "next-auth";
import { authOptions } from "./lib/auth";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 const session = await getServerSession(authOptions);
 return (
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Providers session={session}>
            <Appbar />
            {children}
          </Providers>
        </body>
      </html>
  );
}
